AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  NamesSubmittedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NamesSubmitted
      AttributeDefinitions:
        - AttributeName: NamesID
          AttributeType: S
        - AttributeName: TefilahID
          AttributeType: S
      KeySchema:
        - AttributeName: NamesID
          KeyType: HASH
        - AttributeName: TefilahID
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: Production

  SubmitNameFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: submit_name.lambda_handler
      Role: arn:aws:iam::893545707099:role/GithubActions
      FunctionName: submit-name-function
      Code:
        S3Bucket: my-bucket
        S3Key: path/to/submit_name.zip
      Runtime: python3.12
      MemorySize: 128
      Timeout: 10
Outputs:
  TableName:
    Value: !Ref NamesSubmittedTable
    Export:
      Name: NamesSubmittedTableName

  SubmitNamesFunctionArn:
    Value: !GetAtt SubmitNamesFunction.Arn
    Export:
      Name: SubmitNamesFunctionArn

  UpdateNamesFunctionArn:
    Value: !GetAtt UpdateNamesFunction.Arn
    Export:
      Name: UpdateNamesFunctionArn

  WeeklyEmailFunctionArn:
    Value: !GetAtt WeeklyEmailFunction.Arn
    Export:
      Name: WeeklyEmailFunctionArn
