name: Deploy to Amazon

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write 
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Referencing the secret
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Referencing the secret
        aws-region: ${{ env.AWS_REGION }}
    
    - name: AWS Who Am I
      run: aws sts get-caller-identity
